{
  "name": "express-async-error-wrapper",
  "version": "1.0.4",
  "description": "A stupid wrapper for express routes to catch and call `next()` on any errors thrown.",
  "main": "index.js",
  "repository": "git@github.com:Tethik/express-async-error-wrapper.git",
  "author": "Joakim Uddholm <joakim@uddholm.com>",
  "license": "MIT",
  "private": false,
  "devDependencies": {
    "@types/express": "^4.17.8",
    "express": "^4.16.3",
    "express-async-error-wrapper": "^1.0.1"
  },
  "types": "index.d.ts"
}
